[connections.my_database]
    type="sql"
    dialect="sqlite"
    #username="xxx"
    #password="xxx"
    #host="example.com" # IP or URL
    #port=3306 # Port number
    database="student_grades.db" # Database name